repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.11.12'
    hooks:
    -   id: ruff
        args:
          - --fix
    -   id: ruff-format

-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.9
    hooks:
      - id: uv-export
        name: main dependencies
        args: [--no-dev, --no-hashes, -o, requirements.txt]
        files: pyproject.toml

-   repo: local
    hooks:
      - id: validate-yads-spec
        name: "Validate YADS spec"
        entry: bash
        language: system
        args:
        -   -c
        -   "find examples/specs -name '*.yaml' -print0 | xargs -0 check-jsonschema --schemafile spec/yads_spec_latest.json"
        files: ^(examples/specs/.*\.yaml|spec/yads_spec_latest\.json)$